version: "3"
services:

  tachikoma1:
    hostname: tachikoma1
    image: tachikoma:2.1
    build: .
    environment:
      CONFIG: default
#    volumes:
#      - /var/lib/tachikoma:/home/tachikoma/.tachikoma
    ports:
      - "127.0.0.1:4242:4242"
    networks:
      - local
    restart: always

networks:
  local:
