services:

  tachikoma1:
    hostname: tachikoma1
    image: tachikoma:2.1
    build: .
    env_file: .env
    volumes:
      - .:/services/tachikoma-2.1/sources/tachikoma
    ports:
      - "127.0.0.1:4242:4242"
    networks:
      - local
    restart: always

networks:
  local:
